#!/bin/sh
#
#Start digitpic ...
#

TOUCH=$(cat /sys/class/input/input0/name)
GOODIX=goodix-ts

start() {
if [ $TOUCH  = $GOODIX ]
then

#Prohibit display of cursor
echo -e "\033[?25l"  > /dev/tty1

#close lcd sleep
echo -e "\033[9;0]" > /dev/tty1

export TSLIB_TSDEVICE=/dev/input/event0
export TSLIB_CALIBFILE=/etc/pointercal
export TSLIB_CONFFILE=/etc/ts.conf
export TSLIB_FBDEVICE=/dev/fb0

if [ ! -e /etc/pointercal ]
then
        /usr/bin/ts_calibrate
fi
digitpic /home/MSYH.TTF &
else
        echo lcd not found!
        exit
fi

}
stop() {

killall digitpic /home/MSYH.TTF

}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart|reload)
        stop
        start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?

